#!/bin/bash

#Mahshad Mahdavi, Feb 2019

# generating symbol level LG files from MathML 

if [ $# -lt 2 ]
then
	echo " -----------------------------------------"
        echo "Usage: mml2lg <mmldir> <outdir>"
        echo " -----------------------------------------"
	exit 0
fi

OUTDIR=$2

if ! [ -d $OUTDIR ]
then
	mkdir $OUTDIR
fi


mkdir inkml_temp/
mkdir lg_temp/

python3 process_mml.py $1 inkml_temp/
		
./batch_mml2lg inkml_temp/ lg_temp/ 2> perl_warning.txt

python3 update_nodeTags.py lg_temp/ $OUTDIR


#remove temp folders

rm -r inkml_temp/
rm -r lg_temp/ 
	

      
    



