#!/bin/bash

#Mahshad Mahdavi, Feb 2019

# generating mathML from latex using pandoc then rendering LG from mathml

if [ $# -lt 2 ]
then
	echo " -----------------------------------------"
        echo "Usage: tex2lg <texdir> <lgdir>"
        echo " -----------------------------------------"
	exit 0
fi

OUTDIR=$2

if ! [ -d $OUTDIR ]
then
        mkdir $OUTDIR
fi

mkdir mml_temp/

for file in $1/*.txt
do
        echo "Converting: $file"
        BNAME=`basename $file .txt`
        OUT="$OUTDIR/$BNAME.lg"
        if [ $OUT -ot $file ]
        then
		
		txtDir=$file
		mmlDir="mml_temp/$BNAME.mml"
        	pandoc --mathml --quiet -s $txtDir -o $mmlDir
      	fi
	
done


#convert mml to lg
./mml2symlg mml_temp/ $OUTDIR


rm -r mml_temp


